name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Deploy Static Page
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
          publish_branch: static

      - name: Push server-only branch
        run: |
          # Pobierz main branch lokalnie
          git fetch origin main
          git checkout main

          # Tworzymy orphan branch server
          git checkout --orphan server

          # Usuń wszystko z pustego branchu
          git rm -rf . || true

          # Skopiuj folder server z maina do katalogu głównego
          git checkout main -- server

          # Przenieś pliki z folderu server do root branchu
          mv server/* .
          rm -rf server

          git add .
          git commit -m "Initial commit with server content"
          git push origin server --force
